name: Expo CI CD

on:
  push:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node Modules
        run: yarn install
        
      - name: view actual path
        run: cd ../ | ls -l

      - name: Test
        run: yarn run test
