name: Expo CI CD

on:
  push:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node Modules
        run: yarn install
        
      - name: view tree
        run: tree /home/runner/work/tp_react_ipi/

      - name: Test
        run: yarn run test
